image:
  file: .gitpod/Dockerfile
  context: .gitpod
ports:
  - port: 8080
    onOpen: open-preview
tasks:
- init: |
    cp -R /var/www/html/vendor .
    cp -R /var/www/html/config/docker config/.
    cp -R /var/www/html/storage/database.sqlite storage/.
  command: |
    apachectl start
