image:
  file: .gitpod/Dockerfile
  context: .gitpod
ports:
  - port: 8080
    onOpen: open-preview
tasks:
- init: |
    echo "APP_ENV=docker" > .env
    echo "CMS_LINK_POLICY=secure" >> .env
    cp -R /var/www/html/vendor .
    cp -R /var/www/html/config/docker config/.
    echo 'config/docker' >> .git/info/exclude
    cp -R /var/www/html/storage/database.sqlite storage/.
  command: |
    apachectl start
