image:
  file: .gitpod/Dockerfile
  context: .gitpod
ports:
  - port: 8080
    onOpen: open-preview
tasks:
- init: |
    cp -R /var/www/html/vendor /workspace/october/.
    chown -R gitpod:gitpod /workspace/october/vendor
    touch storage/database.sqlite
    chmod 666 storage/database.sqlite
    php artisan october:up
  command: |
    apachectl start
